name: Secrets

on:
  workflow_dispatch:

jobs:
  top-secret:
    runs-on: ubuntu-latest

    env:
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
    - name: Read a variable
      run: echo "NEWS_API_KEY value is $NEWS_API_KEY"
