name: Secrets

on:
  workflow_dispatch
jobs:
    top-secret:
    runs-on: ubuntu-latest
    env:
       NEWS_API_KEY: ${{vars.NEWS_API_KEY}}
       WEATHER_API_KEY: ${{vars.WEATHER_API_KEY}}
    steps:
     - name: Read a variable
     - echo "NEWS_API_KEY value is ${{env.NEWS_API_KEY}}"